Repository teamBeNU/SSOP_BE, pull requests merged in 2024-10, with the labels that each got.

#52 [FIX] #51 카드 복수 삭제
  src/main/java/SSOP/ssop/controller/CardController.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/service/User/UserService.java
Labels: 🌞 backend, ➕ feat, 📌fix

#54 fix: #53 학생 카드 생성 - 초중고와 대학(원) card_template 분리
  src/main/java/SSOP/ssop/controller/CardController.java
  src/main/java/SSOP/ssop/service/CardService.java
Labels: 🌞 backend, 📌fix

#55 [RELEASE] BE 3차 배포
  src/main/java/SSOP/ssop/controller/CardController.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/service/User/UserService.java
Labels: 🌞 backend

#57 [FEAT] 토큰으로 유저 검색
  src/main/java/SSOP/ssop/config/JwtProvider.java
  src/main/java/SSOP/ssop/controller/UserController.java
  src/main/java/SSOP/ssop/domain/TeamSp/TeamSp.java
  src/main/java/SSOP/ssop/service/User/UserService.java
Labels: 🌞 backend, ➕ feat, 📌fix

#59 [FIX] 카드 조회
  src/main/java/SSOP/ssop/controller/CardController.java
  src/main/java/SSOP/ssop/dto/card/response/CardResponse.java
  src/main/java/SSOP/ssop/dto/card/response/CardStudentResponse.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/utils/CardUtils.java
Labels: 🌞 backend, 📌fix

#62 [FIX] 필터링 한 번에 요청
  src/main/java/SSOP/ssop/controller/SearchController.java
  src/main/java/SSOP/ssop/controller/TeamSp/FilterController.java
  src/main/java/SSOP/ssop/controller/UserController.java
  src/main/java/SSOP/ssop/domain/TeamSp/TeamSp.java
  src/main/java/SSOP/ssop/dto/Search/MemberSearchDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/FilterMemberDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/TeamSpByUserDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/TeamSpMemberDto.java
  src/main/java/SSOP/ssop/repository/TeamSp/FilterRepository.java
  src/main/java/SSOP/ssop/repository/TeamSp/MemberRepository.java
  src/main/java/SSOP/ssop/service/SearchService.java
  src/main/java/SSOP/ssop/service/TeamSp/FilterService.java
  src/main/java/SSOP/ssop/service/TeamSp/TeamSpMemberService.java
  src/main/java/SSOP/ssop/service/TeamSp/TeamSpService.java
  src/main/java/SSOP/ssop/service/User/UserService.java
Labels: 🌞 backend, ➕ feat, 📌fix

#65 [FEAT] 상대 카드 조회 _ 업데이트 시간 추가
  src/main/java/SSOP/ssop/dto/card/response/CardResponse.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/service/LinkShare/LinkShareService.java
  src/main/java/SSOP/ssop/service/MySp/MySpService.java
  src/main/java/SSOP/ssop/utils/CardUtils.java
Labels: 🌞 backend, ➕ feat

#66 [RELEASE] BE 7차 배포
  src/main/java/SSOP/ssop/dto/card/response/CardResponse.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/service/LinkShare/LinkShareService.java
  src/main/java/SSOP/ssop/service/MySp/MySpService.java
  src/main/java/SSOP/ssop/utils/CardUtils.java
Labels: 🌞 backend

#71 [FIX] kakao redirect url 수정
  src/main/java/SSOP/ssop/controller/KakaoController.java
Labels: 🌞 backend, 📌fix
