Repository teamBeNU/SSOP_BE, pull requests merged in 2024-09, with the labels that each got.

#23 [FEAT] #2 Card API
  build.gradle
  src/main/java/SSOP/ssop/controller/CardController.java
  src/main/java/SSOP/ssop/controller/CustomException.java
  src/main/java/SSOP/ssop/controller/GlobalExceptionHandler.java
  src/main/java/SSOP/ssop/controller/TeamSp/MemberController.java
  src/main/java/SSOP/ssop/controller/TeamSp/TeamSpController.java
  src/main/java/SSOP/ssop/controller/TeamSp/TeamSpMemberController.java
  src/main/java/SSOP/ssop/domain/card/Avatar.java
  src/main/java/SSOP/ssop/domain/card/Card.java
  src/main/java/SSOP/ssop/domain/card/CardEssential.java
  src/main/java/SSOP/ssop/domain/card/CardFan.java
  src/main/java/SSOP/ssop/domain/card/CardOptional.java
  src/main/java/SSOP/ssop/domain/card/CardStudent.java
  src/main/java/SSOP/ssop/domain/card/CardWorker.java
  src/main/java/SSOP/ssop/domain/card/Music.java
  src/main/java/SSOP/ssop/domain/card/SNS.java
  src/main/java/SSOP/ssop/domain/card/TemplateEssential.java
  src/main/java/SSOP/ssop/domain/card/TemplateOptional.java
  src/main/java/SSOP/ssop/dto/User/UserDto.java
  src/main/java/SSOP/ssop/dto/card/request/AvatarRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardCreateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardEssentialCreateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardFanCreateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardFanUpdateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardOptionalCreateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardStudentCreateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardStudentUpdateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardUpdateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardWorkerCreateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardWorkerUpdateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/MemoRequest.java
  src/main/java/SSOP/ssop/dto/card/request/SubmitCardRequest.java
  src/main/java/SSOP/ssop/dto/card/response/CardFanResponse.java
  src/main/java/SSOP/ssop/dto/card/response/CardResponse.java
  src/main/java/SSOP/ssop/dto/card/response/CardStudentResponse.java
  src/main/java/SSOP/ssop/dto/card/response/CardWorkerResponse.java
  src/main/java/SSOP/ssop/repository/CardFanRepository.java
  src/main/java/SSOP/ssop/repository/CardStudentRepository.java
  src/main/java/SSOP/ssop/repository/CardWorkerRepository.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/utils/CardUtils.java
Labels: 🌞 backend, ➕ feat, 📌fix

#26 [FIX] TeamSp API
  src/main/java/SSOP/ssop/controller/CardController.java
  src/main/java/SSOP/ssop/controller/TeamSp/FilterController.java
  src/main/java/SSOP/ssop/controller/TeamSp/MemberController.java
  src/main/java/SSOP/ssop/controller/TeamSp/TeamSpController.java
  src/main/java/SSOP/ssop/controller/TeamSp/TeamSpMemberController.java
  src/main/java/SSOP/ssop/controller/UserController.java
  src/main/java/SSOP/ssop/domain/TeamSp/FanOptional.java
  src/main/java/SSOP/ssop/domain/TeamSp/Member.java
  src/main/java/SSOP/ssop/domain/TeamSp/StudentOptional.java
  src/main/java/SSOP/ssop/domain/TeamSp/TeamSp.java
  src/main/java/SSOP/ssop/domain/TeamSp/TeamSpMember.java
  src/main/java/SSOP/ssop/domain/TeamSp/WorkerOptional.java
  src/main/java/SSOP/ssop/domain/User.java
  src/main/java/SSOP/ssop/domain/card/Card.java
  src/main/java/SSOP/ssop/dto/TeamSp/FilterDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/MemberResponse.java
  src/main/java/SSOP/ssop/dto/TeamSp/TeamSpByUserDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/TeamSpMemSortedDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/TeamSpMemberDto.java
  src/main/java/SSOP/ssop/dto/User/PasswordDto.java
  src/main/java/SSOP/ssop/dto/User/UserDto.java
  src/main/java/SSOP/ssop/dto/card/request/SubmitCardRequest.java
  src/main/java/SSOP/ssop/dto/card/response/CardResponse.java
  src/main/java/SSOP/ssop/repository/Card/AvatarRepository.java
  src/main/java/SSOP/ssop/repository/Card/CardFanRepository.java
  src/main/java/SSOP/ssop/repository/Card/CardRepository.java
  src/main/java/SSOP/ssop/repository/Card/CardStudentRepository.java
  src/main/java/SSOP/ssop/repository/Card/CardWorkerRepository.java
  src/main/java/SSOP/ssop/repository/FilterRepository.java
  src/main/java/SSOP/ssop/repository/TeamSp/FilterRepository.java
  src/main/java/SSOP/ssop/repository/TeamSp/MemberRepository.java
  src/main/java/SSOP/ssop/repository/TeamSp/TeamSpMemberRepository.java
  src/main/java/SSOP/ssop/repository/TeamSp/TeamSpRepository.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/service/TeamSp/FilterService.java
  src/main/java/SSOP/ssop/service/TeamSp/MemberService.java
  src/main/java/SSOP/ssop/service/TeamSp/TeamSpMemberService.java
  src/main/java/SSOP/ssop/service/TeamSp/TeamSpService.java
  src/main/java/SSOP/ssop/service/User/UserService.java
  src/main/java/SSOP/ssop/utils/CardUtils.java
Labels: 🌞 backend, ➕ feat, 📌fix

#29 [FIX] #27 카드 api 수정
  .gitignore
  src/main/java/SSOP/ssop/controller/CardController.java
  src/main/java/SSOP/ssop/domain/User.java
  src/main/java/SSOP/ssop/domain/card/CardSaveDetails.java
  src/main/java/SSOP/ssop/dto/User/UserDto.java
  src/main/java/SSOP/ssop/dto/card/response/CardResponse.java
  src/main/java/SSOP/ssop/dto/card/response/CardSaveResponse.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/service/User/UserService.java
  src/main/java/SSOP/ssop/utils/CardUtils.java
  src/main/resources/application-secret.properties
  src/main/resources/application.yml
Labels: 🌞 backend, ➕ feat, 📌fix

#30 [FEAT] #9 kakao social login
  .gitignore
  build.gradle
  src/main/java/SSOP/ssop/controller/AdminController.java
  src/main/java/SSOP/ssop/controller/KakaoController.java
  src/main/java/SSOP/ssop/domain/KakaoUser.java
  src/main/java/SSOP/ssop/domain/OAuthToken.java
  src/main/java/SSOP/ssop/domain/User.java
  src/main/java/SSOP/ssop/dto/User/LoginDto.java
  src/main/java/SSOP/ssop/service/KakaoService.java
  src/main/java/SSOP/ssop/service/User/UserService.java
  src/main/java/SSOP/ssop/utils/DateUtils.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/static/image/kakao_login_button.png
  src/main/resources/static/index.html
  src/main/resources/templates/cards.html
  src/main/resources/templates/users.html
Labels: 🌞 backend, ➕ feat

#36 [FIX] fix/#34-CardAPI
  build.gradle
  src/main/java/SSOP/ssop/config/S3Config.java
  src/main/java/SSOP/ssop/controller/CardController.java
  src/main/java/SSOP/ssop/domain/User.java
  src/main/java/SSOP/ssop/domain/card/Card.java
  src/main/java/SSOP/ssop/dto/MySp/response/MySpGroupResponse.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/service/MySp/MySpService.java
  src/main/java/SSOP/ssop/service/TeamSp/MemberService.java
  src/main/java/SSOP/ssop/service/TeamSp/TeamSpService.java
  src/main/resources/application.yml
Labels: 🌞 backend, ➕ feat, 📌fix

#37 [FIX] #32 cardAPI 수정
  src/main/java/SSOP/ssop/controller/CardController.java
  src/main/java/SSOP/ssop/domain/User.java
  src/main/java/SSOP/ssop/dto/User/UserDto.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/service/User/UserService.java
Labels: 🌞 backend, 📌fix

#39 [FIX] #33 MySpGroupAPI 수정
  src/main/java/SSOP/ssop/domain/MySp/MySp.java
  src/main/java/SSOP/ssop/service/MySp/MySpService.java
Labels: 🌞 backend, 📌fix

#40 [FEAT] 검색 기능 구현 및 템플릿 종류 필터 추가
  src/main/java/SSOP/ssop/controller/CardController.java
  src/main/java/SSOP/ssop/controller/SearchController.java
  src/main/java/SSOP/ssop/controller/TeamSp/FilterController.java
  src/main/java/SSOP/ssop/controller/TeamSp/TeamSpMemberController.java
  src/main/java/SSOP/ssop/domain/TeamSp/Member.java
  src/main/java/SSOP/ssop/domain/TeamSp/TeamSp.java
  src/main/java/SSOP/ssop/domain/TeamSp/TeamSpMember.java
  src/main/java/SSOP/ssop/domain/User.java
  src/main/java/SSOP/ssop/dto/Search/CardSearchDto.java
  src/main/java/SSOP/ssop/dto/Search/KeywordDto.java
  src/main/java/SSOP/ssop/dto/Search/MemberSearchDto.java
  src/main/java/SSOP/ssop/dto/Search/SearchDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/EnterTeamSpDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/FilterDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/MemberEssentialDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/MemberOptionalDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/MemberResponse.java
  src/main/java/SSOP/ssop/dto/TeamSp/TeamSpByUserDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/TeamSpMemSortedDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/TeamSpMemberDto.java
  src/main/java/SSOP/ssop/dto/User/LoginDto.java
  src/main/java/SSOP/ssop/dto/User/PasswordDto.java
  src/main/java/SSOP/ssop/dto/User/UserDto.java
  src/main/java/SSOP/ssop/repository/Card/CardRepository.java
  src/main/java/SSOP/ssop/repository/TeamSp/FilterRepository.java
  src/main/java/SSOP/ssop/repository/TeamSp/MemberRepository.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/service/SearchService.java
  src/main/java/SSOP/ssop/service/TeamSp/FilterService.java
  src/main/java/SSOP/ssop/service/TeamSp/MemberService.java
  src/main/java/SSOP/ssop/service/TeamSp/TeamSpMemberService.java
Labels: 🌞 backend, ➕ feat, 📌fix

#41 [FEAT] #38 그룹명 검색 API
  src/main/java/SSOP/ssop/controller/SearchController.java
  src/main/java/SSOP/ssop/dto/Search/SearchDto.java
  src/main/java/SSOP/ssop/service/SearchService.java
Labels: 🌞 backend, ➕ feat

#43 fix: bSecret 제거
  src/main/java/SSOP/ssop/domain/card/Card.java
  src/main/java/SSOP/ssop/domain/card/CardOptional.java
  src/main/java/SSOP/ssop/domain/card/Music.java
  src/main/java/SSOP/ssop/domain/card/SNS.java
  src/main/java/SSOP/ssop/dto/card/request/CardOptionalCreateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardUpdateRequest.java
  src/main/java/SSOP/ssop/dto/card/response/CardResponse.java
  src/main/java/SSOP/ssop/service/CardService.java
Labels: 🌞 backend, 📌fix

#47 [FIX] 팀스페이스 관련 응답 수정 및 팀스페이스 검색 API 추가 생성
  src/main/java/SSOP/ssop/controller/TeamSp/TeamSpController.java
  src/main/java/SSOP/ssop/controller/TeamSp/TeamSpMemberController.java
  src/main/java/SSOP/ssop/domain/TeamSp/TeamSp.java
  src/main/java/SSOP/ssop/dto/TeamSp/TeamSpInfoDto.java
  src/main/java/SSOP/ssop/service/KakaoService.java
  src/main/java/SSOP/ssop/service/TeamSp/TeamSpMemberService.java
  src/main/java/SSOP/ssop/service/TeamSp/TeamSpService.java
  src/main/resources/application-secret.properties
Labels: 🌞 backend, ➕ feat, 📌fix

#45 [FIX] 카드 bSecret 재추가 및 member bSecret 추가
  src/main/java/SSOP/ssop/domain/TeamSp/Member.java
  src/main/java/SSOP/ssop/domain/card/Card.java
  src/main/java/SSOP/ssop/domain/card/CardOptional.java
  src/main/java/SSOP/ssop/dto/TeamSp/MemberOptionalDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/MemberResponse.java
  src/main/java/SSOP/ssop/dto/card/request/CardOptionalCreateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardUpdateRequest.java
  src/main/java/SSOP/ssop/dto/card/response/CardResponse.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/service/TeamSp/MemberService.java
Labels: 🌞 backend, ➕ feat, 📌fix

#48 [FIX] 알림, 그룹 API 수정
  src/main/java/SSOP/ssop/domain/notification/Notification.java
  src/main/java/SSOP/ssop/repository/Notification/NotificationRepository.java
  src/main/java/SSOP/ssop/service/MySp/MySpService.java
  src/main/java/SSOP/ssop/service/Notification/NotificationService.java
Labels: 🌞 backend, 📌fix

#49 [FIX] 알림 7일 뒤 삭제 수정
  src/main/java/SSOP/ssop/SsopApplication.java
  src/main/java/SSOP/ssop/controller/notification/NotificationController.java
  src/main/java/SSOP/ssop/domain/notification/Notification.java
  src/main/java/SSOP/ssop/dto/notification/NotificationDto.java
  src/main/java/SSOP/ssop/repository/Notification/NotificationRepository.java
  src/main/java/SSOP/ssop/service/Notification/NotificationService.java
  src/main/resources/application.properties
Labels: 🌞 backend, 📌fix

#50 [RELEASE] BE 2차 배포
  src/main/java/SSOP/ssop/SsopApplication.java
  src/main/java/SSOP/ssop/controller/KakaoController.java
  src/main/java/SSOP/ssop/controller/TeamSp/TeamSpController.java
  src/main/java/SSOP/ssop/controller/TeamSp/TeamSpMemberController.java
  src/main/java/SSOP/ssop/controller/notification/NotificationController.java
  src/main/java/SSOP/ssop/domain/TeamSp/Member.java
  src/main/java/SSOP/ssop/domain/TeamSp/TeamSp.java
  src/main/java/SSOP/ssop/domain/card/Card.java
  src/main/java/SSOP/ssop/domain/card/CardOptional.java
  src/main/java/SSOP/ssop/domain/card/Music.java
  src/main/java/SSOP/ssop/domain/card/SNS.java
  src/main/java/SSOP/ssop/domain/notification/Notification.java
  src/main/java/SSOP/ssop/dto/TeamSp/MemberOptionalDto.java
  src/main/java/SSOP/ssop/dto/TeamSp/MemberResponse.java
  src/main/java/SSOP/ssop/dto/TeamSp/TeamSpInfoDto.java
  src/main/java/SSOP/ssop/dto/card/request/CardOptionalCreateRequest.java
  src/main/java/SSOP/ssop/dto/card/request/CardUpdateRequest.java
  src/main/java/SSOP/ssop/dto/card/response/CardResponse.java
  src/main/java/SSOP/ssop/dto/notification/NotificationDto.java
  src/main/java/SSOP/ssop/repository/Notification/NotificationRepository.java
  src/main/java/SSOP/ssop/service/CardService.java
  src/main/java/SSOP/ssop/service/MySp/MySpService.java
  src/main/java/SSOP/ssop/service/Notification/NotificationService.java
  src/main/java/SSOP/ssop/service/TeamSp/MemberService.java
  src/main/java/SSOP/ssop/service/TeamSp/TeamSpMemberService.java
  src/main/java/SSOP/ssop/service/TeamSp/TeamSpService.java
  src/main/resources/application-secret.properties
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🌞 backend
